# Generated by Django 2.2.7 on 2019-11-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_nombre', models.CharField(max_length=200)),
                ('tipo_enfermedad', models.CharField(max_length=200)),
            ],
        ),
    ]
