# Generated by Django 2.2.7 on 2019-11-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_instituto', models.CharField(max_length=400)),
                ('fecha_creacion_historial', models.DateField(auto_now_add=True)),
                ('fecha_ultima_actualizacion', models.DateField()),
            ],
        ),
    ]
