# Generated by Django 2.2.7 on 2019-11-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mujeres', '0002_mujer_paciente_enferma'),
        ('historiales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='mujer_historial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mujeres.Mujer'),
            preserve_default=False,
        ),
    ]
