# Generated by Django 2.2.7 on 2019-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_diagnostico', models.DateField(auto_now_add=True)),
                ('recomendaciones', models.TextField(max_length=900)),
            ],
        ),
    ]
