# Generated by Django 2.2.7 on 2019-11-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctores', '0001_initial'),
        ('historiales', '0001_initial'),
        ('diagnosticos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='doctor_emite_diagnostico',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='doctores.Doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='historial_diagnostico',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='historiales.Historial'),
            preserve_default=False,
        ),
    ]
