# Generated by Django 2.2.7 on 2019-11-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padecimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_padecimiento', models.CharField(max_length=200)),
                ('descripcion_padecimiento', models.TextField(max_length=300)),
                ('intensidad_padecimiento', models.IntegerField()),
            ],
        ),
    ]
