# Generated by Django 2.2.7 on 2019-11-21 02:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('personas', '0003_auto_20191121_0204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='hermanos',
        ),
    ]
