# Generated by Django 2.2.7 on 2019-11-23 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeoInfo', '0001_initial'),
        ('personas', '0006_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ciudad_nacimiento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudades_nacimeinto', to='GeoInfo.Ciudad'),
        ),
    ]
