# Generated by Django 2.2.7 on 2019-11-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_doctor', models.CharField(max_length=200)),
                ('cedula_doctor', models.CharField(max_length=200)),
                ('direccion_doctor', models.CharField(max_length=200)),
                ('telefono_contacto', models.CharField(max_length=200)),
            ],
        ),
    ]
