# Generated by Django 2.2.7 on 2019-11-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_analisis', models.CharField(max_length=200)),
                ('fecha_de_solicitud', models.DateField()),
                ('fecha_resultados', models.DateField(blank=True, null=True)),
                ('resultados', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
