# Generated by Django 2.2.7 on 2019-11-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosticos', '0001_initial'),
        ('analisis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisis',
            name='analisis_del_diagnostico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diagnosticos.Diagnostico'),
            preserve_default=False,
        ),
    ]
