# Generated by Django 2.2.7 on 2019-11-16 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='hermanos',
            field=models.ManyToManyField(related_name='mis_hermanos', to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='madre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_de_la_madre', to='personas.Persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='padre',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_del_padre', to='personas.Persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='pareja',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_pareja', to='personas.Persona'),
        ),
    ]
