# Generated by Django 2.2.7 on 2019-11-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.CharField(max_length=200)),
                ('nombre_enfermedad', models.CharField(max_length=200)),
                ('enfermedad_mortal', models.BooleanField(default=False)),
                ('fecha_deteccion', models.DateField()),
                ('fecha_alta_paciente', models.DateField()),
            ],
        ),
    ]
