# Generated by Django 2.2.7 on 2019-11-23 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='personas.Persona')),
                ('numero_membresia', models.CharField(max_length=10)),
            ],
            bases=('personas.persona',),
        ),
        migrations.AddField(
            model_name='persona',
            name='madre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_de_la_madre', to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='padre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos_del_padre', to='personas.Persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='pareja',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mi_pareja', to='personas.Persona'),
        ),
        migrations.CreateModel(
            name='Hermandad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona_dos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_to_set', to='personas.Persona')),
                ('persona_uno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_from_set', to='personas.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='hermanos',
            field=models.ManyToManyField(related_name='mis_hermanos', through='personas.Hermandad', to='personas.Persona'),
        ),
    ]
