# Generated by Django 2.2.7 on 2019-11-16 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mujer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=400)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_ultima_menstruacion', models.DateField()),
            ],
        ),
    ]
